# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('sno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('sna', models.CharField(max_length=255)),
                ('sarea', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('ar', models.CharField(max_length=255)),
                ('sareaen', models.CharField(max_length=255)),
                ('snaen', models.CharField(max_length=255)),
                ('aren', models.CharField(max_length=255)),
                ('tot', models.IntegerField()),
                ('sbi', models.IntegerField()),
                ('bemp', models.IntegerField()),
                ('act', models.IntegerField()),
                ('mday', models.DateTimeField()),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationInfo',
            fields=[
                ('sno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('sna', models.CharField(max_length=100)),
                ('sarea', models.CharField(max_length=20)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('ar', models.CharField(max_length=100)),
                ('sareaen', models.CharField(max_length=20)),
                ('snaen', models.CharField(max_length=100)),
                ('aren', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'station_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationStats',
            fields=[
                ('sno', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tot', models.IntegerField()),
                ('sbi', models.IntegerField()),
                ('bemp', models.IntegerField()),
                ('act', models.IntegerField()),
                ('mday', models.DateTimeField()),
            ],
            options={
                'db_table': 'station_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbikeStatsLog',
            fields=[
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('sno', models.IntegerField()),
                ('tot', models.IntegerField()),
                ('sbi', models.IntegerField()),
                ('bemp', models.IntegerField()),
                ('act', models.IntegerField()),
                ('mday', models.DateTimeField()),
            ],
            options={
                'db_table': 'ubike_stats_log',
                'managed': False,
            },
        ),
    ]
